"use client"
import { useHeaderContext } from "@/app/_common/contexts/header.context"
import { useCallback, useEffect, useRef, useState } from "react"
import { IdProps } from "@/app/_common/types/id-props.type"
import { Content } from "@/app/_common/models/content/content.model"
import { ContentService } from "../../../_services/content.service"
import { Button } from "primereact/button"
import { Card } from "primereact/card"
import { Skeleton } from "primereact/skeleton"
import { Message } from "primereact/message"
import { Divider } from "primereact/divider"
import { ContentStatus } from "@/app/_common/models/content/content-status.enum"
import Link from "next/link"
import { _routes } from "@/app/(admin)/_configs/_routes"
import { Toast } from "primereact/toast"
import { Presentation } from "./presentation.component"
import { Text } from "./text.component"
import { FilesItem } from "./files-item.component"

export default function Documents({ params }: IdProps) {
  const { setHeaderInfo } = useHeaderContext()
  const [content, setContent] = useState<Content | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [contentId, setContentId] = useState<string | null>(null)
  const toast = useRef<Toast>(null)

  const loadContent = useCallback(async () => {
    if (!contentId) return
    try {
      setLoading(true)
      setError(null)
      const data = await ContentService.findById(contentId)
      setContent(data)
    } catch (err: any) {
      setError(err.message || "Error loading content")
    } finally {
      setLoading(false)
    }
  }, [contentId])

  useEffect(() => {
    setHeaderInfo("Documents", "Documents Generated by Artificial Intelligence")
    const resolveParams = async () => {
      const resolvedParams = await params
      setContentId(resolvedParams.id)
    }
    resolveParams()
  }, [setHeaderInfo, params])

  useEffect(() => {
    if (contentId) {
      loadContent()
    }
  }, [contentId, loadContent])

  if (loading) {
    return (
      <div className="p-6">
        <Card>
          <Skeleton height="2rem" className="mb-2" />
          <Skeleton height="1rem" className="mb-4" />
          <Skeleton height="20rem" />
        </Card>
      </div>
    )
  }

  if (error) {
    return (
      <div className="p-6">
        <Message severity="error" text={error} />
        <Button
          label="Retry"
          icon="pi pi-refresh"
          onClick={loadContent}
          className="mt-4"
        />
      </div>
    )
  }

  if (!content) {
    return (
      <div className="p-6">
        <Message severity="warn" text="Content not found" />
      </div>
    )
  }

  return (
    <>
      <Toast ref={toast} />
      <header className="justify-between mb-10">
        <div className="grow">
          <Link href={_routes.contents}>
            <button
              aria-label="none"
              className="rounded-lg bg-white dark:bg-darkblack-600 dark:text-white p-4 inline-flex items-center justify-center text-base text-bgray-600 border border-transparent hover:border-success-300 transition duration-300 ease-in-out"
            >
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M15 6L9 12L15 18"
                  stroke="#A0AEC0"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
              <span> Back</span>
            </button>
          </Link>
        </div>
      </header>
      <Presentation content={content} />
      <FilesItem content={content} />
      <Text content={content} />

      {content.messageError && content.status == ContentStatus.ERROR && (
        <>
          <Divider />
          <Message severity="error" text={content.messageError} />
        </>
      )}
    </>
  )
}
