export enum ContentStatus {
  PENDING = 0,
  DOWNLOADING_MEDIA = 1,
  CONVERTING_AUDIO = 2,
  TRANSCRIBING_AUDIO = 3,
  GENERATING_TEXT = 4,
  REQUEST_PRESENTATION = 5,
  GENERATING_PRESENTATION = 6,
  DOWNLOADING_PRESENTATION = 7,
  COMPLETED = 8,
  ERROR = 9,
  CANCELED = 10,
  PARTIAL = 11,
}
