import { Db } from "mongodb"
import { MigrationInterface } from "mongo-migrate-ts"
import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()

export class add_config_telegram1732321044171 implements MigrationInterface {
  public async up(db: Db): Promise<any> {
    let $titleGroup = "Telegram"
    let $nameConfig = ""
    let group = await prisma.configGroup.findUnique({
      where: {
        title: $titleGroup,
      },
    })
    if (!group) {
      group = await prisma.configGroup.create({
        data: {
          title: $titleGroup,
        },
      })
    }

    $nameConfig = "telegram-bot-token"
    await prisma.config.create({
      data: {
        configGroupId: group.id,
        name: $nameConfig,
        title: "Bot Token Telegram",
        description:
          "Token generated by Telegram's BotFather User using the /newbot command. Enter the Telegram bot token if you want to recover your GenEdu password using the 'Forgot password' method.",
        type: "password",
        jsonOptions: undefined,
        value: "",
        classAdd: undefined,
      },
    })

    $nameConfig = "telegram-bot-username"
    await prisma.config.create({
      data: {
        configGroupId: group.id,
        name: $nameConfig,
        title: "Bot Username Telegram",
        description: "Username you created on Telegram's BotFather",
        type: "text",
        jsonOptions: undefined,
        value: "GeneduBot",
        classAdd: undefined,
      },
    })

    $nameConfig = "telegram-verification"
    await prisma.config.create({
      data: {
        configGroupId: group.id,
        name: $nameConfig,
        title: "Telegram Verification",
        description: "Check Telegram to confirm that the user registration.",
        type: "radio",
        jsonOptions: { "0": "No", "1": "Yes" },
        value: "0",
        classAdd: undefined,
      },
    })
  }

  public async down(db: Db): Promise<any> {
    await prisma.config.delete({ where: { name: "telegram-bot-token" } })
    await prisma.config.delete({ where: { name: "telegram-bot-username" } })
    await prisma.config.delete({ where: { name: "telegram-verification" } })
    await prisma.configGroup.delete({ where: { title: "Telegram" } })
  }
}
